### ISSUE TITLE
Random error on joining

### ISSUE THREAD

**Issue by Korinocho** [BGHDDevelopment/PlayerBalancer#25]
Every time someone joins, bungee give some errors, they are appearing 1 time per join, and using any version of minecraft. However, no disconnections occurs.
Using PlayerBalancer 2.3.0, Waterfall #448 and Java 16.

> [03:41:50 WARN]: Error dispatching event ServerConnectEvent(player=test, target=BungeeServerInfo(name=auth, socketAddress=localhost/127.0.0.1:20000, restricted=false), reason=JOIN_PROXY, request=net.md_5.bungee.api.ServerConnectRequest@6ac3cf8d, cancelled=false) to listener com.jaimemartz.playerbalancer.listeners.ServerConnectListener@d3b0397
java.lang.NullPointerException: Cannot invoke "com.jaimemartz.playerbalancer.connection.ProviderType.requestTarget(com.jaimemartz.playerbalancer.PlayerBalancer, com.jaimemartz.playerbalancer.section.ServerSection, java.util.List, net.md_5.bungee.api.connection.ProxiedPlayer)" because "provider" is null
        at com.jaimemartz.playerbalancer.connection.ConnectionIntent.fetchServer(ConnectionIntent.java:85) ~[?:?]
        at com.jaimemartz.playerbalancer.connection.ConnectionIntent.execute(ConnectionIntent.java:52) ~[?:?]
        at com.jaimemartz.playerbalancer.listeners.ServerConnectListener.onConnect(ServerConnectListener.java:52) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:48) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:304) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:294) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at net.md_5.bungee.UserConnection.connect(UserConnection.java:268) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:563) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by BGHDDevelopment** [comment]
Hey! Weird error, does this occur when using this build? https://www.spigotmc.org/resources/playerbalancer.55011/download?version=387212

I want to just see if it's an issue with the last update or if something bigger is going on. I can test locally this weekend.

**Comment by Korinocho** [comment]
Its been happening since 2.2.2, i can confirm. Yesterday i still had it installed and thought that 2.3.0 will fix this error.

**Comment by BGHDDevelopment** [comment]
Can you send a `/balancer paste all` so I can take a look over the config?
I will be testing on Saturday so want to make sure I can recreate it as much as possible on my end.

**Comment by Korinocho** [comment]
[13:25:35 INFO]: PlayerBalancer configuration link: https://haste.zneix.eu/jahavozuxa
[13:25:35 INFO]: BungeeCord configuration link: https://haste.zneix.eu/amakyfoqud
[13:25:36 INFO]: An internal error occurred while attempting to perform this command
[13:25:36 ERROR]: java.lang.Exception: Unexpected response code 413
[13:25:36 ERROR]:       at com.jaimemartz.playerbalancer.utils.HastebinPaste.paste(HastebinPaste.java:41)
[13:25:36 ERROR]:       at com.jaimemartz.playerbalancer.helper.PasteHelper$3.paste(PasteHelper.java:90)
[13:25:36 ERROR]:       at com.jaimemartz.playerbalancer.helper.PasteHelper.send(PasteHelper.java:111)
[13:25:36 ERROR]:       at com.jaimemartz.playerbalancer.commands.MainCommand.execute(MainCommand.java:33)
[13:25:36 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(Unknown Source)
[13:25:36 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(Unknown Source)
[13:25:36 ERROR]:       at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(Unknown Source)
[13:25:36 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(Unknown Source)
[13:25:36 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(Unknown Source)
[13:25:36 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.start(Unknown Source)
[13:25:36 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(Unknown Source)
[13:25:36 ERROR]:       at net.md_5.bungee.Bootstrap.main(Unknown Source)
[13:25:36 INFO]: Could not create the paste, try again...

**Comment by BGHDDevelopment** [comment]
Thanks for the logs, I am going to try and test locally tonight.

**Comment by BGHDDevelopment** [comment]
Sorry for the long delay, we have tested locally using the same config and bungee builds with no errors appearing on our end. Do you have any other possible changes that we can test on our end that could be causing this? (EX: bungee changes, etc)

**Comment by BGHDDevelopment** [comment]
As this is not reproducible I will be closing this. Thanks for waiting.
