### ISSUE TITLE
All schemas except RANDOM providers will report an error and cannot be used

### ISSUE THREAD

**Issue by HansOffice** [BGHDDevelopment/PlayerBalancer#30]
The error message is as follows,It's what I'm missing in the affiliation?

20:22:29 [警告] Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@650b5f0e, receiver=hanPO), cancelled=false, tag=playerbalancer:main) to listener com.jaimemartz.playerbalancer.listeners.PluginMessageListener@7769d9b6
java.lang.NoClassDefFoundError: com/imaginarycode/minecraft/redisbungee/RedisBungeeAPI
	at com.jaimemartz.playerbalancer.helper.NetworkManager.getPlayers(NetworkManager.java:18)
	at com.jaimemartz.playerbalancer.connection.provider.types.progressive.ProgressiveFillerProvider.requestTarget(ProgressiveFillerProvider.java:20)
	at com.jaimemartz.playerbalancer.connection.ProviderType$7.requestTarget(ProviderType.java:78)
	at com.jaimemartz.playerbalancer.connection.ConnectionIntent.fetchServer(ConnectionIntent.java:85)
	at com.jaimemartz.playerbalancer.connection.ConnectionIntent.execute(ConnectionIntent.java:52)
	at com.jaimemartz.playerbalancer.connection.ConnectionIntent.simple(ConnectionIntent.java:133)
	at com.jaimemartz.playerbalancer.listeners.PluginMessageListener.onPluginMessage(PluginMessageListener.java:63)
	at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:264)
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:79)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.imaginarycode.minecraft.redisbungee.RedisBungeeAPI
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

**Comment by HansOffice** [comment]
And the BungeeCord version is the latest version just available on spigot today

**Comment by HansOffice** [comment]
And the BungeeCord version is the latest version just available on spigot today

**Comment by BGHDDevelopment** [comment]
Do you have redis bungee enabled in the config?

**Comment by HansOffice** [comment]
Saw that and really turned this on. Excuse me ow, because I do not know much English is completely manual translation of a look at a problem, so there is such a problem awa

**Comment by BGHDDevelopment** [comment]
So when you set redis bungee to false does it work?
