### ISSUE TITLE
Error on 1.20.2 XCord servers

### ISSUE THREAD

**Issue by LoliColleen** [BGHDDevelopment/PlayerBalancer#39]
XCord is a fork of BungeeCord
When a player quit the proxy:

[21:23:20] [epollEventLoopGroup-3-7/INFO]: [/61.183.81.131:64480|RenXingYu] -> UpstreamBridge has disconnected
[21:23:20] [epollEventLoopGroup-3-7/WARN]: Error dispatching event ServerKickEvent(cancelled=true, player=RenXingYu, kickedFrom=BungeeServerInfo(name=SkyBattle#2, socketAddress=/127.0.0.1:26003, restricted=false), kickReasonComponent=[TextComponent{text=Proxy lost connection to server., BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null, reset=true)}], cancelServer=BungeeServerInfo(name=SkyBattleLobby#1, socketAddress=/127.0.0.1:26001, restricted=false), state=CONNECTED, cause=LOST_CONNECTION) to listener com.jaimemartz.playerbalancer.listeners.ServerKickListener@67a0ff25
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
	at net.md_5.bungee.netty.ChannelWrapper.getEncodeProtocol(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at net.md_5.bungee.UserConnection.sendPacketQueued(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at net.md_5.bungee.UserConnection.sendMessage(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at net.md_5.bungee.UserConnection.sendMessage(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at net.md_5.bungee.UserConnection.sendMessage(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at net.md_5.bungee.UserConnection.sendMessage(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at com.jaimemartz.playerbalancer.utils.MessageUtils.send(MessageUtils.java:13) ~[?:?]
	at com.jaimemartz.playerbalancer.utils.MessageUtils.send(MessageUtils.java:22) ~[?:?]
	at com.jaimemartz.playerbalancer.listeners.ServerKickListener$1.connect(ServerKickListener.java:74) ~[?:?]
	at com.jaimemartz.playerbalancer.connection.ConnectionIntent.execute(ConnectionIntent.java:54) ~[?:?]
	at com.jaimemartz.playerbalancer.listeners.ServerKickListener.onKick(ServerKickListener.java:86) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at net.md_5.bungee.event.EventBus.post(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at net.md_5.bungee.connection.DownstreamBridge.disconnected(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at net.md_5.bungee.netty.HandlerBoss.channelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at q.channelInactive(Unknown Source) ~[XCord.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[21:23:20] [epollEventLoopGroup-3-7/INFO]: [/61.183.81.131:64480|RenXingYu] <-> DownstreamBridge <-> [SkyBattle#2] has disconnected
[21:23:20] [epollEventLoopGroup-3-7/INFO]: [RenXingYu|/61.183.81.131:64480] <-> ServerConnector [SkyBattleLobby#1] has connected
[21:23:20] [epollEventLoopGroup-3-7/WARN]: No client connected for pending server!
[21:23:20] [epollEventLoopGroup-3-7/INFO]: [RenXingYu|/61.183.81.131:64480] <-> ServerConnector [SkyBattleLobby#1] has disconnected

**Comment by BGHDDevelopment** [comment]
https://github.com/BGHDDevelopment/PlayerBalancer/issues/40#issuecomment-1901757502

Going to continue this over in the other issue, please reply over there. I am unable to reproduce it on my end.
