### ISSUE TITLE
[error]player left the game

### ISSUE THREAD

**Issue by Blskk** [BGHDDevelopment/PlayerBalancer#40]
waterfall log:
`[10:49:01 INFO]: [/XXX:13878|Lantiann] -> UpstreamBridge has disconnected
[10:49:01 WARN]: Error dispatching event ServerKickEvent(cancelled=false, player=Lantiann, kickedFrom=BungeeServerInfo(name=lobby, socketAddress=/0.0.0.0:22043, restricted=false), reason=TextComponent{text=Proxy lost connection to server., BaseComponent(color=, font=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null, reset=true)}, cancelServer=null, state=CONNECTED, cause=LOST_CONNECTION) to listener com.jaimemartz.playerbalancer.listeners.ServerKickListener@26b3eb48
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftEncoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
        at net.md_5.bungee.netty.ChannelWrapper.getEncodeProtocol(ChannelWrapper.java:51) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.UserConnection.sendPacketQueued(UserConnection.java:195) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:562) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:511) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:499) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at com.jaimemartz.playerbalancer.utils.MessageUtils.send(MessageUtils.java:13) ~[?:?]
        at com.jaimemartz.playerbalancer.listeners.ServerKickListener.getSection(ServerKickListener.java:122) ~[?:?]
        at com.jaimemartz.playerbalancer.listeners.ServerKickListener.onKick(ServerKickListener.java:63) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.connection.DownstreamBridge.disconnected(DownstreamBridge.java:130) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:61) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-560.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:e927093:560]
        at java.lang.Thread.run(Thread.java:842) [?:?]
[10:49:01 INFO]: [/XXX:13878|Lantiann] <-> DownstreamBridge <-> [lobby] has disconnected
[10:49:02 INFO]: [/XXX:13901] <-> InitialHandler has pinged
>`

**Comment by BGHDDevelopment** [comment]
This is a known issue with the latest bungee builds. I am just awaiting some free time to investigate the error. Are you having any negative effects or things not working, or is it just the stack trace?

**Comment by Blskk** [comment]
> 这是最新蹦极版本的已知问题。我只是在等待一些空闲时间来调查错误。您是否有任何负面影响或无法正常工作，或者只是堆栈跟踪？

No other issues

**Comment by BGHDDevelopment** [comment]
Just tested and I am unable to reproduce. Can you give any other details on when this exactly happens?
![explorer_mrr5kGFfYI](https://github.com/BGHDDevelopment/PlayerBalancer/assets/16854333/afbca452-8b41-4f56-b645-77cb5e4e9607)

**Comment by BGHDDevelopment** [comment]
[PB2.3.5.zip](https://github.com/BGHDDevelopment/PlayerBalancer/files/13996807/PB2.3.5.zip)
If you want you can try this version, however I only added a try and catch to see if the error can be hidden. Without reproducing it I can't find a cause.

**Comment by Blskk** [comment]
> [PB2.3.5.zip](https://github.com/BGHDDevelopment/PlayerBalancer/files/13996807/PB2.3.5.zip) If you want you can try this version, however I only added a try and catch to see if the error can be hidden. Without reproducing it I can't find a cause.

Yes, it successfully solved my problem

**Comment by Blskk** [comment]
> [PB2.3.5.zip](https://github.com/BGHDDevelopment/PlayerBalancer/files/13996807/PB2.3.5.zip) If you want you can try this version, however I only added a try and catch to see if the error can be hidden. Without reproducing it I can't find a cause.

Yes, it successfully solved my problem
