### ISSUE TITLE
Undefined Error

### ISSUE THREAD

**Issue by pur23** [BGHDDevelopment/PlayerBalancer#44]
Error:
[22:03:16 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@783ec989, id=20, owner=com.jaimemartz.playerbalancer.PlayerBalancer@1ddd3478, task=com.jaimemartz.playerbalancer.ping.PingTactic$1$$Lambda$206/0x00007f832438ef20@3267c77d, delay=0, period=0, running=true) encountered an exception
com.google.gson.JsonIOException: Failed making field 'java.awt.Color#value' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:38) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.getAdapter(Gson.java:556) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.getAdapter(Gson.java:556) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.getAdapter(Gson.java:556) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.fromJson(Gson.java:1226) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:24) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:13) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.fromJson(Gson.java:1300) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:211) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:30) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at com.jaimemartz.playerbalancer.utils.ServerListPing.ping(ServerListPing.java:113) ~[?:?]
        at com.jaimemartz.playerbalancer.ping.PingTactic$1.lambda$ping$0(PingTactic.java:19) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @665bfb8a
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]
        at java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:35) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        ... 39 more

**Comment by BGHDDevelopment** [comment]
Is this using the updated download from today? Try re-downloading for me and see if that fixes it. The update I released today should fix this issue on newer java versions.

Also, make sure you're using the latest bungeecord version.

**Comment by pur23** [comment]
where. Release shows only update on jan 20 not today

**Comment by BGHDDevelopment** [comment]
As it was a hotfix the release version did not change, you should be able to just redownload the jar files and they will be updated.

**Comment by pur23** [comment]
Okay, it works, you're the best!
Quick answer without much additional information. this is how I want support in my life =D
